# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Dict, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .create_session import CreateSession
from .dataset_initial_state_query import DatasetInitialStateQuery
from .dataset_ready import DatasetReady
from .download_urls import DownloadUrls
from .embedding_data import EmbeddingData
from .files_status import FilesStatus
from .general_de import GeneralDE
from .heatmap import Heatmap
from .highly_variable_genes import HighlyVariableGenes
from .input_types import (
    CellLabelsSearchOptions,
    DatasetSearchOptions,
    GetDatasetEmbeddingDataInput,
    GetGeneralDiffInput,
    GetHighlyVariableGenesInput,
    LookupCellsSearch,
    LookupDatasetsFiltersInput,
    LookupDatasetsSearchInput,
    LookupLabelsFilters,
    PostHeatmapInput,
    ResolveDatasetLabelsetOrder,
    SaveDatasetSessionInput,
)
from .lookup_cells import LookupCells
from .md_commons_query import MDCommonsQuery
from .md_ready import MDReady
from .search_datasets import SearchDatasets


class _Client(BaseClient):
    def search_datasets(
        self,
        options: Union[Optional[DatasetSearchOptions], UnsetType] = UNSET,
        search: Union[Optional[LookupDatasetsSearchInput], UnsetType] = UNSET,
        filter: Union[Optional[LookupDatasetsFiltersInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> SearchDatasets:
        query = ""
        variables: Dict[str, object] = {
            "options": options,
            "search": search,
            "filter": filter,
        }
        response = self.execute(
            query=query, operation_name="SearchDatasets", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return SearchDatasets.model_validate(data)

    def lookup_cells(
        self,
        options: CellLabelsSearchOptions,
        filter: Union[Optional[LookupLabelsFilters], UnsetType] = UNSET,
        search: Union[Optional[LookupCellsSearch], UnsetType] = UNSET,
        **kwargs: Any
    ) -> LookupCells:
        query = ""
        variables: Dict[str, object] = {
            "options": options,
            "filter": filter,
            "search": search,
        }
        response = self.execute(
            query=query, operation_name="LookupCells", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return LookupCells.model_validate(data)

    def download_urls(self, dataset_id: str, **kwargs: Any) -> DownloadUrls:
        query = ""
        variables: Dict[str, object] = {"datasetId": dataset_id}
        response = self.execute(
            query=query, operation_name="DownloadUrls", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DownloadUrls.model_validate(data)

    def dataset_initial_state_query(
        self,
        dataset_id: str,
        labelset_order: Union[Optional[ResolveDatasetLabelsetOrder], UnsetType] = UNSET,
        **kwargs: Any
    ) -> DatasetInitialStateQuery:
        query = ""
        variables: Dict[str, object] = {
            "datasetId": dataset_id,
            "labelsetOrder": labelset_order,
        }
        response = self.execute(
            query=query,
            operation_name="DatasetInitialStateQuery",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return DatasetInitialStateQuery.model_validate(data)

    def create_session(
        self, data: SaveDatasetSessionInput, **kwargs: Any
    ) -> CreateSession:
        query = ""
        variables: Dict[str, object] = {"data": data}
        response = self.execute(
            query=query, operation_name="CreateSession", variables=variables, **kwargs
        )
        _data = self.get_data(response)
        return CreateSession.model_validate(_data)

    def md_commons_query(self, dataset_id: str, **kwargs: Any) -> MDCommonsQuery:
        query = ""
        variables: Dict[str, object] = {"datasetId": dataset_id}
        response = self.execute(
            query=query, operation_name="MDCommonsQuery", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return MDCommonsQuery.model_validate(data)

    def embedding_data(
        self, dataset_id: str, options: GetDatasetEmbeddingDataInput, **kwargs: Any
    ) -> EmbeddingData:
        query = ""
        variables: Dict[str, object] = {"datasetId": dataset_id, "options": options}
        response = self.execute(
            query=query, operation_name="EmbeddingData", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return EmbeddingData.model_validate(data)

    def highly_variable_genes(
        self, options: GetHighlyVariableGenesInput, dataset_id: str, **kwargs: Any
    ) -> HighlyVariableGenes:
        query = ""
        variables: Dict[str, object] = {"options": options, "datasetId": dataset_id}
        response = self.execute(
            query=query,
            operation_name="HighlyVariableGenes",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return HighlyVariableGenes.model_validate(data)

    def files_status(self, dataset_id: str, **kwargs: Any) -> FilesStatus:
        query = ""
        variables: Dict[str, object] = {"datasetId": dataset_id}
        response = self.execute(
            query=query, operation_name="FilesStatus", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return FilesStatus.model_validate(data)

    def general_de(
        self, options: GetGeneralDiffInput, dataset_id: str, **kwargs: Any
    ) -> GeneralDE:
        query = ""
        variables: Dict[str, object] = {"options": options, "datasetId": dataset_id}
        response = self.execute(
            query=query, operation_name="GeneralDE", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GeneralDE.model_validate(data)

    def heatmap(
        self, options: PostHeatmapInput, dataset_id: str, **kwargs: Any
    ) -> Heatmap:
        query = ""
        variables: Dict[str, object] = {"options": options, "datasetId": dataset_id}
        response = self.execute(
            query=query, operation_name="Heatmap", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Heatmap.model_validate(data)

    def dataset_ready(self, dataset_id: str, **kwargs: Any) -> DatasetReady:
        query = ""
        variables: Dict[str, object] = {"datasetId": dataset_id}
        response = self.execute(
            query=query, operation_name="DatasetReady", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DatasetReady.model_validate(data)

    def md_ready(self, dataset_id: str, **kwargs: Any) -> MDReady:
        query = ""
        variables: Dict[str, object] = {"datasetId": dataset_id}
        response = self.execute(
            query=query, operation_name="MDReady", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return MDReady.model_validate(data)
