# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class CreateSession(BaseModel):
    save_dataset_session: "CreateSessionSaveDatasetSession" = Field(
        alias="saveDatasetSession"
    )


class CreateSessionSaveDatasetSession(BaseModel):
    id: str
    name: str
    dataset_type: Optional[str] = Field(alias="datasetType")
    description: Optional[str]
    cell_count: int = Field(alias="cellCount")
    labelsets: List["CreateSessionSaveDatasetSessionLabelsets"]
    typename__: Literal["DatasetModel"] = Field(alias="__typename")


class CreateSessionSaveDatasetSessionLabelsets(BaseModel):
    id: str
    name: str
    mode: str
    description: Optional[str]
    annotation_method: Optional[str] = Field(alias="annotationMethod")
    algorithm_name: Optional[str] = Field(alias="algorithmName")
    algorithm_version: Optional[str] = Field(alias="algorithmVersion")
    algorithm_repo_url: Optional[str] = Field(alias="algorithmRepoUrl")
    reference_location: Optional[str] = Field(alias="referenceLocation")
    reference_description: Optional[str] = Field(alias="referenceDescription")
    labels: List["CreateSessionSaveDatasetSessionLabelsetsLabels"]
    typename__: Literal["LabelsetModel"] = Field(alias="__typename")


class CreateSessionSaveDatasetSessionLabelsetsLabels(BaseModel):
    id: str
    name: str
    count: int
    color: Optional[str]
    full_name: Optional[str] = Field(alias="fullName")
    ontology_term_exists: Optional[bool] = Field(alias="ontologyTermExists")
    ontology_term: Optional[str] = Field(alias="ontologyTerm")
    ontology_term_id: Optional[str] = Field(alias="ontologyTermId")
    category_full_name: Optional[str] = Field(alias="categoryFullName")
    category_ontology_term_exists: Optional[bool] = Field(
        alias="categoryOntologyTermExists"
    )
    category_ontology_term: Optional[str] = Field(alias="categoryOntologyTerm")
    category_ontology_term_id: Optional[str] = Field(alias="categoryOntologyTermId")
    marker_genes: Optional[List[str]] = Field(alias="markerGenes")
    canonical_marker_genes: Optional[List[str]] = Field(alias="canonicalMarkerGenes")
    synonyms: Optional[List[str]]
    rationale: Optional[str]
    rationale_dois: Optional[List[str]] = Field(alias="rationaleDois")
    ontology_assessment: Optional[str] = Field(alias="ontologyAssessment")
    typename__: Literal["LabelModel"] = Field(alias="__typename")


CreateSession.model_rebuild()
CreateSessionSaveDatasetSession.model_rebuild()
CreateSessionSaveDatasetSessionLabelsets.model_rebuild()
