# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class EmbeddingData(BaseModel):
    dataset_session: "EmbeddingDataDatasetSession" = Field(alias="datasetSession")


class EmbeddingDataDatasetSession(BaseModel):
    embedding_data: "EmbeddingDataDatasetSessionEmbeddingData" = Field(
        alias="embeddingData"
    )


class EmbeddingDataDatasetSessionEmbeddingData(BaseModel):
    obs_ids: List[int] = Field(alias="obsIds")
    xy_array: List[float] = Field(alias="xyArray")
    x_max: float = Field(alias="xMax")
    x_min: float = Field(alias="xMin")
    y_max: float = Field(alias="yMax")
    y_min: float = Field(alias="yMin")
    gene_expression: List[float] = Field(alias="geneExpression")
    expression_max: Optional[float] = Field(alias="expressionMax", default=None)
    expression_min: Optional[float] = Field(alias="expressionMin", default=None)
    in_selection_major: List[bool] = Field(alias="inSelectionMajor", default_factory=list)
    in_selection_minor: List[bool] = Field(alias="inSelectionMinor", default_factory=list)
    annotations: List["EmbeddingDataDatasetSessionEmbeddingDataAnnotations"]

    @property
    def positions(self) -> List["EmbeddingDataDatasetSessionEmbeddingDataPositions"]:
        return [
            EmbeddingDataDatasetSessionEmbeddingDataPositions(x=x, y=y)
            for x, y in zip(self.xy_array[::2], self.xy_array[1::2])
        ]


class EmbeddingDataDatasetSessionEmbeddingDataPositions(BaseModel):
    x: float
    y: float


class EmbeddingDataDatasetSessionEmbeddingDataAnnotations(BaseModel):
    name: str
    labels: List[str] = Field(default_factory=list)
    label_ids: List[str] = Field(alias="labelIds")


EmbeddingData.model_rebuild()
EmbeddingDataDatasetSession.model_rebuild()
EmbeddingDataDatasetSessionEmbeddingData.model_rebuild()
