# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel


class EmbeddingData(BaseModel):
    dataset_session: "EmbeddingDataDatasetSession" = Field(alias="datasetSession")


class EmbeddingDataDatasetSession(BaseModel):
    embedding_data: "EmbeddingDataDatasetSessionEmbeddingData" = Field(
        alias="embeddingData"
    )


class EmbeddingDataDatasetSessionEmbeddingData(BaseModel):
    obs_ids: List[int] = Field(alias="obsIds")
    positions: List["EmbeddingDataDatasetSessionEmbeddingDataPositions"]
    gene_expression: List[float] = Field(alias="geneExpression")
    in_selection_major: List[bool] = Field(alias="inSelectionMajor", default_factory=list)
    in_selection_minor: List[bool] = Field(alias="inSelectionMinor", default_factory=list)
    annotations: List["EmbeddingDataDatasetSessionEmbeddingDataAnnotations"]


class EmbeddingDataDatasetSessionEmbeddingDataPositions(BaseModel):
    x: float
    y: float


class EmbeddingDataDatasetSessionEmbeddingDataAnnotations(BaseModel):
    name: str
    labels: List[str]
    label_ids: List[str] = Field(alias="labelIds")


EmbeddingData.model_rebuild()
EmbeddingDataDatasetSession.model_rebuild()
EmbeddingDataDatasetSessionEmbeddingData.model_rebuild()
