# Generated by ariadne-codegen
# Source: queries.graphql

from pydantic import Field

from .base_model import BaseModel


class FilesStatus(BaseModel):
    dataset_session: "FilesStatusDatasetSession" = Field(alias="datasetSession")


class FilesStatusDatasetSession(BaseModel):
    md_files_status: str = Field(alias="mdFilesStatus")


FilesStatus.model_rebuild()
