# Generated by ariadne-codegen
# Source: queries.graphql

from pydantic import Field

from .base_model import BaseModel


class GeneralDE(BaseModel):
    dataset_session: "GeneralDEDatasetSession" = Field(alias="datasetSession")


class GeneralDEDatasetSession(BaseModel):
    general_differential_expressions: str = Field(
        alias="generalDifferentialExpressions"
    )


GeneralDE.model_rebuild()
