# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Literal

from pydantic import Field

from .base_model import BaseModel


class Heatmap(BaseModel):
    dataset_session: "HeatmapDatasetSession" = Field(alias="datasetSession")


class HeatmapDatasetSession(BaseModel):
    heatmap: "HeatmapDatasetSessionHeatmap"


class HeatmapDatasetSessionHeatmap(BaseModel):
    obs_ids: List[int] = Field(alias="obsIds")
    annotations: List[str]
    is_in_selections: List[bool] = Field(alias="isInSelections")
    genes: List[str]
    scores: List[float]
    top_genes_by_selection: List["HeatmapDatasetSessionHeatmapTopGenesBySelection"] = (
        Field(alias="topGenesBySelection")
    )
    typename__: Literal["Heatmap"] = Field(alias="__typename")


class HeatmapDatasetSessionHeatmapTopGenesBySelection(BaseModel):
    genes: List[str]
    selection_name: str = Field(alias="selectionName")
    typename__: Literal["HeatmapTopGenesBySelection"] = Field(alias="__typename")


Heatmap.model_rebuild()
HeatmapDatasetSession.model_rebuild()
HeatmapDatasetSessionHeatmap.model_rebuild()
