# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class HighlyVariableGenes(BaseModel):
    dataset_session: "HighlyVariableGenesDatasetSession" = Field(alias="datasetSession")


class HighlyVariableGenesDatasetSession(BaseModel):
    highly_variable_genes: List[
        "HighlyVariableGenesDatasetSessionHighlyVariableGenes"
    ] = Field(alias="highlyVariableGenes")


class HighlyVariableGenesDatasetSessionHighlyVariableGenes(BaseModel):
    name: str
    dispersion: float
    highly_variable: Optional[bool] = Field(alias="highlyVariable", default=None)
    typename__: Literal["HighlyVariableGeneRow"] = Field(alias="__typename")


HighlyVariableGenes.model_rebuild()
HighlyVariableGenesDatasetSession.model_rebuild()
