# Generated by ariadne-codegen
# Source: https://celltype.info/graphql

from typing import Annotated, Any, List, Optional, Union

from pydantic import Field, PlainSerializer

from .base_model import BaseModel, Upload


class ResolveDatasetLabelsetOrder(BaseModel):
    field: str
    order: str


class CellLabelsSearchOptions(BaseModel):
    offset: Optional[int] = None
    limit: Optional[int] = None
    sort: Optional[List["CellLabelsSearchSort"]] = None


class CellLabelsSearchSort(BaseModel):
    field: str
    order: str


class LookupLabelsFilters(BaseModel):
    metadata: Optional[List["SearchLabelByMetadataArgs"]] = None


class SearchLabelByMetadataArgs(BaseModel):
    field: str
    values: List[str]


class LookupCellsSearch(BaseModel):
    name: Optional[str] = None
    fields: Optional[List[str]] = None


class DatasetSearchOptions(BaseModel):
    offset: Optional[int] = None
    limit: Optional[int] = None
    sort: Optional[List["DatasetSearchSort"]] = None


class DatasetSearchSort(BaseModel):
    field: str
    order: str


class LookupDatasetsFiltersInput(BaseModel):
    metadata: Optional[List["SearchByMetadataArgs"]] = None
    labelset: Optional[List[str]] = None


class SearchByMetadataArgs(BaseModel):
    field: str
    values: List[str]


class LookupDatasetsSearchInput(BaseModel):
    cell_types: Optional[List[str]] = Field(alias="cellTypes", default=None)
    name: Optional[str] = None
    project_name: Optional[str] = Field(alias="projectName", default=None)
    project_description: Optional[str] = Field(alias="projectDescription", default=None)


class DatasetObjectInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    cell_count: Optional[int] = Field(alias="cellCount", default=None)
    gene_count: Optional[int] = Field(alias="geneCount", default=None)
    dataset_type: Optional[str] = Field(alias="datasetType", default=None)
    description: Optional[str] = None
    labelsets: Optional[List["LabelsetWithLabelsObjectInput"]] = None
    default_embedding: Optional[str] = Field(alias="defaultEmbedding", default=None)


class GetDatasetEmbeddingDataInput(BaseModel):
    embedding: str
    scale_max_plan: float = Field(alias="scaleMaxPlan")
    selection_gene: Optional[str] = Field(alias="selectionGene", default=None)
    selection_key_major: Optional[str] = Field(alias="selectionKeyMajor", default=None)
    selection_key_minor: Optional[str] = Field(alias="selectionKeyMinor", default=None)
    session_id: Optional[str] = Field(alias="sessionId", default=None)
    labelsets: Optional[List[str]] = None


class GetGeneralDiffInput(BaseModel):
    labelset_id: str = Field(alias="labelsetId")
    session_id: str = Field(alias="sessionId")
    random_seed: float = Field(alias="randomSeed")


class GetHighlyVariableGenesInput(BaseModel):
    offset: float
    limit: float
    gene_name_filter: Optional[str] = Field(alias="geneNameFilter", default=None)
    use_genes_pattern: Optional[bool] = Field(alias="useGenesPattern", default=None)
    sort_by: Optional[str] = Field(alias="sortBy", default=None)
    sort_order: Optional[str] = Field(alias="sortOrder", default=None)


class LabelObjectInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    full_name: Optional[str] = Field(alias="fullName", default=None)
    color: Optional[str] = None
    count: Optional[int] = None
    ontology_term: Optional[str] = Field(alias="ontologyTerm", default=None)
    ontology_term_id: Optional[str] = Field(alias="ontologyTermId", default=None)
    ontology_term_exists: Optional[bool] = Field(
        alias="ontologyTermExists", default=None
    )
    ontology_assessment: Optional[str] = Field(alias="ontologyAssessment", default=None)
    category_ontology_term: Optional[str] = Field(
        alias="categoryOntologyTerm", default=None
    )
    category_ontology_term_id: Optional[str] = Field(
        alias="categoryOntologyTermId", default=None
    )
    category_ontology_term_exists: Optional[bool] = Field(
        alias="categoryOntologyTermExists", default=None
    )
    category_full_name: Optional[str] = Field(alias="categoryFullName", default=None)
    rationale: Optional[str] = None
    rationale_dois: Optional[List[str]] = Field(alias="rationaleDois", default=None)
    marker_genes: Optional[List[str]] = Field(alias="markerGenes", default=None)
    canonical_marker_genes: Optional[List[str]] = Field(
        alias="canonicalMarkerGenes", default=None
    )
    synonyms: Optional[List[str]] = None
    average_conf_score: Optional[float] = Field(alias="averageConfScore", default=None)


class LabelsetWithLabelsObjectInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    mode: Optional[str] = None
    status: Optional[str] = None
    order: Optional[int] = None
    description: Optional[str] = None
    algorithm_name: Optional[str] = Field(alias="algorithmName", default=None)
    algorithm_version: Optional[str] = Field(alias="algorithmVersion", default=None)
    algorithm_repo_url: Optional[str] = Field(alias="algorithmRepoUrl", default=None)
    annotation_method: Optional[str] = Field(alias="annotationMethod", default=None)
    reference_location: Optional[str] = Field(alias="referenceLocation", default=None)
    reference_description: Optional[str] = Field(
        alias="referenceDescription", default=None
    )
    labels: Optional[List["LabelObjectInput"]] = None


class PostHeatmapInput(BaseModel):
    diff_key: str = Field(alias="diffKey")
    n_genes: Optional[int] = Field(alias="nGenes", default=None)
    scale_max_plan: Optional[float] = Field(alias="scaleMaxPlan", default=None)
    genes_filter: Optional[List[str]] = Field(alias="genesFilter", default=None)
    use_genes_pattern: Optional[bool] = Field(alias="useGenesPattern", default=None)
    session_id: Optional[str] = Field(alias="sessionId", default=None)
    include_reference_selection: Optional[bool] = Field(
        alias="includeReferenceSelection", default=None
    )
    selection_key: Optional[str] = Field(alias="selectionKey", default=None)
    max_p_value: Optional[float] = Field(alias="maxPValue", default=None)
    focus_labels: Optional[List[str]] = Field(alias="focusLabels", default=None)


class SaveDatasetSessionInput(BaseModel):
    session_id: str = Field(alias="sessionId")
    dataset: "DatasetObjectInput"


CellLabelsSearchOptions.model_rebuild()
LookupLabelsFilters.model_rebuild()
DatasetSearchOptions.model_rebuild()
LookupDatasetsFiltersInput.model_rebuild()
DatasetObjectInput.model_rebuild()
LabelsetWithLabelsObjectInput.model_rebuild()
SaveDatasetSessionInput.model_rebuild()
