# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Literal

from pydantic import Field

from .base_model import BaseModel


class MDCommonsQuery(BaseModel):
    dataset_session: "MDCommonsQueryDatasetSession" = Field(alias="datasetSession")


class MDCommonsQueryDatasetSession(BaseModel):
    embeddings: List["MDCommonsQueryDatasetSessionEmbeddings"]


class MDCommonsQueryDatasetSessionEmbeddings(BaseModel):
    name: str
    typename__: Literal["EmbeddingGroup"] = Field(alias="__typename")


MDCommonsQuery.model_rebuild()
MDCommonsQueryDatasetSession.model_rebuild()
