# Generated by ariadne-codegen
# Source: https://celltype.info/graphql

from enum import Enum


class FeedbackExplanationType(str, Enum):
    agree = "agree"
    disagree = "disagree"
    split = "split"
    merge = "merge"
    refine = "refine"
    idk = "idk"
